import { StrictPropsWithChildren } from '@/type'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '관리자 랜딩페이지',
  description: 'Generated by create next app',
}

export default function layout({ children }: StrictPropsWithChildren) {
  return (
    <main className="w-full h-screen flex justify-center items-center bg-[#FBFBFB]">
      {children}
    </main>
  )
}
