import { StrictPropsWithChildren } from '@/type'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '관리자 랜딩페이지',
  description: 'Generated by create next app',
}

export default function layout({ children }: StrictPropsWithChildren) {
  return (
    <main className="mt-54 w-full h-[calc(100%-54px)] flex justify-center items-center">
      {children}
    </main>
  )
}
