import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '관리자 랜딩페이지',
  description: 'Generated by create next app',
}

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className="h-full flex justify-center items-center">{children}</main>
  )
}
