import { StrictPropsWithChildren } from '@/type'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '관리자 어린이집 설정 페이지',
  description: 'Generated by create next app',
}

export default function layout({ children }: StrictPropsWithChildren) {
  return (
    <main className="relative font-sans overflow-scroll h-screen w-screen p-100">
      <div className="fixed top-200 left-100 w-226 h-226 rounded-full bg-[#DDA82A] blur-[158.5px]" />
      <div className="fixed bottom-100 right-100 w-226 h-226 rounded-full bg-[#FFAB2D] blur-[158.5px]" />
      {children}
    </main>
  )
}
