import { Qna } from './type'

export const qna: Qna[] = [
  {
    id: 1,
    title: '안뇽하세요 저는 문의사항입니다? 1',
    content: '내용 1',
    date: '2024-01-01',
    answered: true,
    author: 'User 1',
  },
  {
    id: 2,
    title: '안뇽하세요 저는 문의사항입니다? 2',
    content: '내용 2',
    date: '2024-01-02',
    answered: false,
    author: 'User 2',
  },
  {
    id: 3,
    title: '안뇽하세요 저는 문의사항입니다? 3',
    content: '내용 3',
    date: '2024-01-03',
    answered: true,
    author: 'User 3',
  },
  {
    id: 4,
    title: '안뇽하세요 저는 문의사항입니다? 4',
    content: '내용 4',
    date: '2024-01-04',
    answered: false,
    author: 'User 4',
  },
  {
    id: 5,
    title: '안뇽하세요 저는 문의사항입니다? 5',
    content: '내용 5',
    date: '2024-01-05',
    answered: true,
    author: 'User 5',
  },
  {
    id: 6,
    title: '안뇽하세요 저는 문의사항입니다? 6',
    content: '내용 6',
    date: '2024-01-06',
    answered: false,
    author: 'User 6',
  },
  {
    id: 7,
    title: '안뇽하세요 저는 문의사항입니다? 7',
    content: '내용 7',
    date: '2024-01-07',
    answered: true,
    author: 'User 7',
  },
  {
    id: 8,
    title: '안뇽하세요 저는 문의사항입니다? 8',
    content: '내용 8',
    date: '2024-01-08',
    answered: false,
    author: 'User 8',
  },
  {
    id: 9,
    title: '안뇽하세요 저는 문의사항입니다? 9',
    content: '내용 9',
    date: '2024-01-09',
    answered: true,
    author: 'User 9',
  },
  {
    id: 10,
    title: '안뇽하세요 저는 문의사항입니다? 10',
    content: '내용 10',
    date: '2024-01-10',
    answered: true,
    author: 'User 10',
  },
  {
    id: 11,
    title: '안뇽하세요 저는 문의사항입니다? 11',
    content: '내용 11',
    date: '2024-01-11',
    answered: false,
    author: 'User 11',
  },
]

export const totalItems = qna.length
