name: CLOVIDER Client CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: ENV File 설정중
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env
        shell: bash

      - name: 카카오 컨테이너 레지스트리에 로그인중...
        run: |
          docker login kids-in-company.kr-central-2.kcr.dev --username ${{ secrets.KAKAO_ACCESS_ID }} --password ${{ secrets.KAKAO_ACCESS_SECRET }}

      - name: Docker 이미지 빌드중..
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: false
          tags: clovider-fe-app:latest

      - name: Docker 이미지 태그 설정중..
        run: |
          docker tag clovider-fe-app:latest kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:latest

      - name: 카카오 컨테이너 레지스트리에 푸시중..
        run: |
          docker push kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:latest
