name: CLOVIDER Client CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: ENV File 설정중
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env
        shell: bash

      - name: 도커 레지스트리 로그인중...
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GLUE_PROJECT }}
          username: ${{ secrets.ACCESS_ID }}
          password: ${{ secrets.ACCESS_SECRET }}

      - name: 카카오 클라우드에 빌드 및 푸시중..
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ secrets.GLUE_PROJECT }}/glue-repository/glue-client:${{ github.sha }}

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: PEM 키 설정중
        run: |
          echo "${{ secrets.KAKAO_SSH_KEY_PEM }}" > kakao_ssh_key.pem
          chmod 600 kakao_ssh_key.pem
        shell: bash

      - name: Kakao VM에 배포중..
        run: |
          ssh -o StrictHostKeyChecking=no -i kakao_ssh_key.pem ubuntu@210.109.55.28 << 'EOF'
            docker login kids-in-company.kr-central-2.kcr.dev --username ${{ secrets.KAKAO_ACCESS_ID }} --password ${{ secrets.KAKAO_ACCESS_SECRET }}
            docker pull ${{ secrets.GLUE_PROJECT }}/glue-repository/glue-client:${{ github.sha }}
            docker stop clovider-fe-app || true
            docker rm clovider-fe-app || true
            docker run -d --name clovider-fe-app -p 80:80 ${{ secrets.GLUE_PROJECT }}/glue-repository/glue-client:${{ github.sha }}
          EOF
        shell: bash
