name: CLOVIDER Client CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: ENV File 설정중
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env
        shell: bash

      - name: 카카오 컨테이너 레지스트리에 로그인중...
        run: |
          docker login kids-in-company.kr-central-2.kcr.dev --username ${{ secrets.KAKAO_ACCESS_ID }} --password ${{ secrets.KAKAO_ACCESS_SECRET }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker 이미지 빌드중...
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: false
          tags: clovider-fe-app:${{ github.sha }}
          load: true
          
      - name: 빌드된 이미지 확인중..
        run: |
          docker images

      - name: Docker 이미지 태그 설정중..
        run: |
          docker tag clovider-fe-app:${{ github.sha }} kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:${{ github.sha }}
          
      - name: 카카오 컨테이너 레지스트리에 푸시중..
        run: |
          docker push kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:${{ github.sha }}
          
  update-manifest-state:
    runs-on: self-hosted
    needs: build-and-push-image
    steps:
      - name: Checkout kic-k8s Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_PROJECT }}/kic-k8s
          token: ${{ secrets.ACTIONS_TOKEN }}
          ref: "main"

      - name: Install yq
        run: sudo snap install yq

      - name: Update image tag in deployment file
        run: |
          yq e ".spec.template.spec.containers[0].image = \"kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-fe-app:${{ github.sha }}\"" -i clovider-app/fe-deployment.yaml
          
      - name: Commit and Push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add clovider-app/fe-deployment.yaml
          git commit -m "[skip ci] Update image tag to ${{ github.sha }}"
          git push
